/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://p3mmkkfvmngvdpwisxqe5lxyhq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2tgawlhwuzbgtlnircmzgktqbi",
    "aws_cognito_identity_pool_id": "us-west-2:1151eb55-91db-4a29-b97d-f3a07009da2e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ZrsQIV5WV",
    "aws_user_pools_web_client_id": "2bgj4e6q1b1i037ms23efka667",
    "oauth": {}
};


export default awsmobile;
